public  class CheckDatatypes {
    //creater a method
    public void MethodBoolean() {
    Boolean   checkBoolean=true;
    system.debug('checkBoolean is==>' + checkBoolean );
    }
    //create second method
    public void MethodInteger(){
    Integer varFirst=1;
    Integer varSecond=2;
    system.debug(varFirst + '  ' +varSecond);
    }
    //create third method
    public void StringMethod(){
     String varName='Name';
     String varName2='Ayshe';
     system.debug('First one is ' + varName  +  ' ' + 'and second one is ' +   varName2);

    }
}